### ISSUE TITLE
Own SSL certificates (option A) doesn't seem to work?

### ISSUE THREAD

**Issue by mbewley** [l3iggs/docker-owncloud#106]
I'm trying to set up using your Option A, and having trouble. I'm using a docker-compose file to mount my SSL certificates at /root/sslKeys as described, but I get the following error:

oc                 | AH00526: Syntax error on line 143 of /etc/httpd/conf/extra/httpd-ssl.conf:
oc                 | SSLCertificateFile: file '/root/sslKeys/fullchain.pem' does not exist or is empty

Should fullchain.pem be needed when I have my own certificates? How do I stop apache from looking for them?

docker-compose extract...

```
owncloud-server:
  container_name: oc
  image: l3iggs/owncloud:9.1.0-1
  links:
    - postgres
  ports:
  - '443:443'
  environment:
    - START_MYSQL=false
  volumes:
    - /mnt/data/owncloud/data:/usr/share/webapps/owncloud/data
    - /mnt/data/owncloud/config/config.php:/usr/share/webapps/owncloud/config/config.php
    - ./ssl:/root/sslKeys:ro

```
